#### Business Problem Statement
*A leading retail company wants to better understand its customers’ shopping behavior in order to improve sales, customer satisfaction, and long-term loyalty. The management team has noticed changes in purchasing patterns across demographics, product categories, and sales channels (online vs. offline). They are particularly interested in uncovering which factors, such as discounts, reviews, seasons, or payment preferences, drive consumer decisions and repeat purchases.*

*You are tasked with analyzing the company’s consumer behavior dataset to answer the following overarching business question:*

*“How can the company leverage consumer shopping data to identify trends, improve customer engagement, and optimize marketing and product strategies?”*

In [56]:
import numpy as np;
import pandas as pd;

In [57]:
df=pd.read_csv('customer_shopping_behavior.csv')

In [58]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [59]:
df.shape

(3900, 18)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [61]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [62]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [63]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [64]:
df['Category'].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [65]:
df['Size'].unique()

array(['L', 'S', 'M', 'XL'], dtype=object)

In [66]:
df['Location'].unique()

array(['Kentucky', 'Maine', 'Massachusetts', 'Rhode Island', 'Oregon',
       'Wyoming', 'Montana', 'Louisiana', 'West Virginia', 'Missouri',
       'Arkansas', 'Hawaii', 'Delaware', 'New Hampshire', 'New York',
       'Alabama', 'Mississippi', 'North Carolina', 'California',
       'Oklahoma', 'Florida', 'Texas', 'Nevada', 'Kansas', 'Colorado',
       'North Dakota', 'Illinois', 'Indiana', 'Arizona', 'Alaska',
       'Tennessee', 'Ohio', 'New Jersey', 'Maryland', 'Vermont',
       'New Mexico', 'South Carolina', 'Idaho', 'Pennsylvania',
       'Connecticut', 'Utah', 'Virginia', 'Georgia', 'Nebraska', 'Iowa',
       'South Dakota', 'Minnesota', 'Washington', 'Wisconsin', 'Michigan'],
      dtype=object)

In [67]:
df['Shipping Type'].unique()

array(['Express', 'Free Shipping', 'Next Day Air', 'Standard',
       '2-Day Shipping', 'Store Pickup'], dtype=object)

In [68]:
df['Payment Method'].unique()

array(['Venmo', 'Cash', 'Credit Card', 'PayPal', 'Bank Transfer',
       'Debit Card'], dtype=object)

In [69]:

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [70]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda a:a.fillna(a.median()))

In [71]:
#checking the null values 
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [72]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'},inplace=True)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [73]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [74]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [75]:
f_m={'Fortnightly':14, 'Weekly':7, 'Annually':365, 'Quarterly': 90, 'Bi-Weekly':14,'Monthely': 30, 'Every 3 Month':90}
df['frequency_of_purchases']=df['frequency_of_purchases'].map(f_m)
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,14.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,90.0

In [76]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   object
 17  frequency_of_purchases  2763 non-null   float64
dtypes: float64(2), int64(4), object(12)
memory usage: 548.6+ KB

In [79]:
df=df.drop('promo_code_used',axis=1)

In [80]:

df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,14.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,90.0

In [83]:
!python -m pip install mysql-connector-python
import mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.5 MB 840.3 kB/s eta 0:00:20
   - -------------------------------------- 0.8/16.5 MB 946.6 kB/s eta 0:00:17
   - -------------------------------------- 0.8/16.5 MB 946.6 kB/s eta 0:00:17
   -- ------------------------------------- 1.0/16.5 MB 825.4 kB/s eta 0:00:19
   --- ------------------------------------ 1.3/16.5 MB 806.6 kB/s eta 0:00:19
   --- ------------------------------------ 1.6/16.5 MB 893.4 kB/s eta 0:00:17
   ---- ----------------------------------- 1.8/16.5 MB 923.7 kB/s eta 0:00:16
   ---- ----------------------------------- 1.8/16.5 MB 923.7 kB/s eta 0:00:16
   ----- ---------------------------------- 2.1/16.5 MB 916.4 kB/s eta 0:00:16
   ----- ---------------------------------- 2.1/16.5 MB 916.4 kB/s eta 0:00:16
   ----- ---------------------------------- 2.4/16.5 MB 819.4 kB/s eta 0:00:18
   ----- ---------------------------------- 2.4/16.5 MB 819.4 kB/s eta 0:00:18
   ----- ---------------------------------- 2.4/16.5 MB 819.4 kB/s eta 0:00:18
   ----- ---------------------------------- 2.4/16.5 MB 819.4 kB/s eta 0:00:18
   ------ --------------------------------- 2.6/16.5 MB 717.2 kB/s eta 0:00:20
   ------ --------------------------------- 2.6/16.5 MB 717.2 kB/s eta 0:00:20
   ------ --------------------------------- 2.6/16.5 MB 717.2 kB/s eta 0:00:20
   ------ --------------------------------- 2.9/16.5 MB 675.9 kB/s eta 0:00:21
   ------ --------------------------------- 2.9/16.5 MB 675.9 kB/s eta 0:00:21
   ------ --------------------------------- 2.9/16.5 MB 675.9 kB/s eta 0:00:21
   ------ --------------------------------- 2.9/16.5 MB 675.9 kB/s eta 0:00:21
   ------- -------------------------------- 3.1/16.5 MB 600.9 kB/s eta 0:00:23
   ------- -------------------------------- 3.1/16.5 MB 600.9 kB/s eta 0:00:23
   ------- -------------------------------- 3.1/16.5 MB 600.9 kB/s eta 0:00:23
   ------- -------------------------------- 3.1/16.5 MB 600.9 kB/s eta 0:00:23
   -------- ------------------------------- 3.4/16.5 MB 551.1 kB/s eta 0:00:24
   -------- ------------------------------- 3.4/16.5 MB 551.1 kB/s eta 0:00:24
   -------- ------------------------------- 3.4/16.5 MB 551.1 kB/s eta 0:00:24
   -------- ------------------------------- 3.4/16.5 MB 551.1 kB/s eta 0:00:24
   -------- ------------------------------- 3.7/16.5 MB 529.0 kB/s eta 0:00:25
   -------- ------------------------------- 3.7/16.5 MB 529.0 kB/s eta 0:00:25
   -------- ------------------------------- 3.7/16.5 MB 529.0 kB/s eta 0:00:25
   --------- ------------------------------ 3.9/16.5 MB 514.6 kB/s eta 0:00:25
   --------- ------------------------------ 3.9/16.5 MB 514.6 kB/s eta 0:00:25
   --------- ------------------------------ 3.9/16.5 MB 514.6 kB/s eta 0:00:25
   --------- ------------------------------ 3.9/16.5 MB 514.6 kB/s eta 0:00:25
   ---------- ----------------------------- 4.2/16.5 MB 491.1 kB/s eta 0:00:26
   ---------- ----------------------------- 4.2/16.5 MB 491.1 kB/s eta 0:00:26
   ---------- ----------------------------- 4.2/16.5 MB 491.1 kB/s eta 0:00:26
   ---------- ----------------------------- 4.5/16.5 MB 481.8 kB/s eta 0:00:26
   ---------- ----------------------------- 4.5/16.5 MB 481.8 kB/s eta 0:00:26
   ---------- ----------------------------- 4.5/16.5 MB 481.8 kB/s eta 0:00:26
   ---------- ----------------------------- 4.5/16.5 MB 481.8 kB/s eta 0:00:26
   ----------- ---------------------------- 4.7/16.5 MB 475.5 kB/s eta 0:00:25
   ----------- ---------------------------- 4.7/16.5 MB 475.5 kB/s eta 0:00:25
   ----------- ---------------------------- 4.7/16.5 MB 475.5 kB/s eta 0:00:25
   ----------- ---------------------------- 4.7/16.5 MB 475.5 kB/s eta 0:00:25
   ------------ --------------------------- 5.0/16.5 MB 461.3 kB/s eta 0:00:26
   ------------ --------------------------- 5.0/16.5 MB 461.3 kB/s eta 0:00:26
   ------------ --------------------------- 5.0/16.5 MB 461.3 kB/s eta 0:00:26
   ------------ --------------------------- 5.0/16.5 MB 461.3 kB/s eta 0:00:26
   ------------ --------------------------- 5.2/16.5 MB 448.3 kB/s eta 0:00:26
   ------------- -------------------------- 5.5/16.5 MB 457.2 kB/s eta 0:00:25
   ------------- -------------------------- 5.5/16.5 MB 457.2 kB/s eta 0:00:25
   ------------- -------------------------- 5.8/16.5 MB 464.0 kB/s eta 0:00:24
   ------------- -------------------------- 5.8/16.5 MB 464.0 kB/s eta 0:00:24
   ------------- -------------------------- 5.8/16.5 MB 464.0 kB/s eta 0:00:24
   -------------- ------------------------- 6.0/16.5 MB 462.3 kB/s eta 0:00:23
   -------------- ------------------------- 6.0/16.5 MB 462.3 kB/s eta 0:00:23
   -------------- ------------------------- 6.0/16.5 MB 462.3 kB/s eta 0:00:23
   -------------- ------------------------- 6.0/16.5 MB 462.3 kB/s eta 0:00:23
   --------------- ------------------------ 6.3/16.5 MB 456.8 kB/s eta 0:00:23
   --------------- ------------------------ 6.6/16.5 MB 465.8 kB/s eta 0:00:22
   --------------- ------------------------ 6.6/16.5 MB 465.8 kB/s eta 0:00:22
   ---------------- ----------------------- 6.8/16.5 MB 473.9 kB/s eta 0:00:21
   ----------------- ---------------------- 7.1/16.5 MB 482.9 kB/s eta 0:00:20
   ----------------- ---------------------- 7.1/16.5 MB 482.9 kB/s eta 0:00:20
   ----------------- ---------------------- 7.1/16.5 MB 482.9 kB/s eta 0:00:20
   ----------------- ---------------------- 7.3/16.5 MB 480.0 kB/s eta 0:00:20
   ----------------- ---------------------- 7.3/16.5 MB 480.0 kB/s eta 0:00:20
   ----------------- ---------------------- 7.3/16.5 MB 480.0 kB/s eta 0:00:20
   ----------------- ---------------------- 7.3/16.5 MB 480.0 kB/s eta 0:00:20
   ------------------ --------------------- 7.6/16.5 MB 471.6 kB/s eta 0:00:19
   ------------------ --------------------- 7.6/16.5 MB 471.6 kB/s eta 0:00:19
   ------------------- -------------------- 7.9/16.5 MB 470.3 kB/s eta 0:00:19
   ------------------- -------------------- 7.9/16.5 MB 470.3 kB/s eta 0:00:19
   ------------------- -------------------- 7.9/16.5 MB 470.3 kB/s eta 0:00:19
   ------------------- -------------------- 8.1/16.5 MB 471.6 kB/s eta 0:00:18
   ------------------- -------------------- 8.1/16.5 MB 471.6 kB/s eta 0:00:18
   ------------------- -------------------- 8.1/16.5 MB 471.6 kB/s eta 0:00:18
   -------------------- ------------------- 8.4/16.5 MB 469.8 kB/s eta 0:00:18
   -------------------- ------------------- 8.4/16.5 MB 469.8 kB/s eta 0:00:18
   -------------------- ------------------- 8.4/16.5 MB 469.8 kB/s eta 0:00:18
   -------------------- ------------------- 8.4/16.5 MB 469.8 kB/s eta 0:00:18
   -------------------- ------------------- 8.7/16.5 MB 460.1 kB/s eta 0:00:18
   -------------------- ------------------- 8.7/16.5 MB 460.1 kB/s eta 0:00:18
   -------------------- ------------------- 8.7/16.5 MB 460.1 kB/s eta 0:00:18
   -------------------- ------------------- 8.7/16.5 MB 460.1 kB/s eta 0:00:18
   --------------------- ------------------ 8.9/16.5 MB 453.6 kB/s eta 0:00:17
   --------------------- ------------------ 8.9/16.5 MB 453.6 kB/s eta 0:00:17
   --------------------- ------------------ 8.9/16.5 MB 453.6 kB/s eta 0:00:17
   --------------------- ------------------ 8.9/16.5 MB 453.6 kB/s eta 0:00:17
   --------------------- ------------------ 8.9/16.5 MB 453.6 kB/s eta 0:00:17
   ---------------------- ----------------- 9.2/16.5 MB 444.2 kB/s eta 0:00:17
   ---------------------- ----------------- 9.4/16.5 MB 451.3 kB/s eta 0:00:16
   ---------------------- ----------------- 9.4/16.5 MB 451.3 kB/s eta 0:00:16
   ----------------------- ---------------- 9.7/16.5 MB 454.0 kB/s eta 0:00:16
   ----------------------- ---------------- 9.7/16.5 MB 454.0 kB/s eta 0:00:16
   ----------------------- ---------------- 9.7/16.5 MB 454.0 kB/s eta 0:00:16
   ------------------------ --------------- 10.0/16.5 MB 455.6 kB/s eta 0:00:15
   ------------------------ --------------- 10.0/16.5 MB 455.6 kB/s eta 0:00:15
   ------------------------ --------------- 10.2/16.5 MB 459.0 kB/s eta 0:00:14
   ------------------------ --------------- 10.2/16.5 MB 459.0 kB/s eta 0:00:14
   ------------------------- -------------- 10.5/16.5 MB 463.4 kB/s eta 0:00:14
   -------------------------- ------------- 10.7/16.5 MB 470.4 kB/s eta 0:00:13
   -------------------------- ------------- 11.0/16.5 MB 474.1 kB/s eta 0:00:12
   -------------------------- ------------- 11.0/16.5 MB 474.1 kB/s eta 0:00:12
   --------------------------- ------------ 11.3/16.5 MB 479.2 kB/s eta 0:00:11
   --------------------------- ------------ 11.5/16.5 MB 485.6 kB/s eta 0:00:11
   ----------------------------- ---------- 12.1/16.5 MB 502.3 kB/s eta 0:00:09
   ----------------------------- ---------- 12.1/16.5 MB 502.3 kB/s eta 0:00:09
   ----------------------------- ---------- 12.3/16.5 MB 507.6 kB/s eta 0:00:09
   ------------------------------ --------- 12.6/16.5 MB 512.2 kB/s eta 0:00:08
   ------------------------------- -------- 12.8/16.5 MB 518.7 kB/s eta 0:00:08
   ------------------------------- -------- 13.1/16.5 MB 526.1 kB/s eta 0:00:07
   -------------------------------- ------- 13.4/16.5 MB 529.2 kB/s eta 0:00:06
   --------------------------------- ------ 13.6/16.5 MB 535.1 kB/s eta 0:00:06
   --------------------------------- ------ 13.9/16.5 MB 542.2 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 542.2 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 543.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 543.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 544.3 kB/s eta 0:00:04
   ---------------------------------- ----- 14.4/16.5 MB 544.3 kB/s eta 0:00:04
   ---------------------------------- ----- 14.4/16.5 MB 544.3 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 541.4 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 541.4 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 541.4 kB/s eta 0:00:04
   ------------------------------------ --- 14.9/16.5 MB 538.9 kB/s eta 0:00:03
   ------------------------------------ --- 14.9/16.5 MB 538.9 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 538.5 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 538.5 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 538.5 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 538.5 kB/s eta 0:00:03
   ------------------------------------- -- 15.5/16.5 MB 533.4 kB/s eta 0:00:02
   -------------------------------------- - 15.7/16.5 MB 537.0 kB/s eta 0:00:02
   -------------------------------------- - 15.7/16.5 MB 537.0 kB/s eta 0:00:02
   -------------------------------------- - 15.7/16.5 MB 537.0 kB/s eta 0:00:02
   -------------------------------------- - 16.0/16.5 MB 537.3 kB/s eta 0:00:01
   -------------------------------------- - 16.0/16.5 MB 537.3 kB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 535.0 kB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 535.0 kB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 528.3 kB/s  0:00:30
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [85]:
conn=mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="tiger",
    database='customer_behaviour'
)

In [86]:
#imstall required liberaries 
%pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [87]:
#import libraries
from sqlalchemy import create_engine

In [89]:
#create connection to my sql
engine=create_engine('mysql+pymysql://root:tiger@localhost/customer_behaviour')

In [90]:
#upload dataframe to mysql

df.to_sql(
    name="customers", #table name
    con=engine,
    if_exists="replace",   #replace / append/ fail
    index=False
)

3900